### PR TITLE
videojs-contrib-hls deprecated (#205)

### PR DESCRIPTION
**Pull request by goatandsheep**
upgraded videojs version + removed instances of videojs-contrib-hls

### CODE REVIEW

**Comment by goatandsheep** [comment]
https://github.com/surmon-china/vue-video-player/issues/205

**Comment by surmon-china** [comment]
Thx!

**Comment by shady-xia** [comment]
大佬，啥时候更新新版本呀

**Comment by ttshivers** [comment]
Why was this pull request closed and not merged? The repository still hasn't updated the videojs version.

**Pull request closed without merging**
